#!/usr/bin/env ansible-playbook

- name: Gather prerequisites 
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Create EBS Volumes
  hosts: localhost
  become: False
  vars:
      instance_id: "i-0451390c76c495a2e"
      region: "us-east-1"
  tasks:
      - ec2_vol:
            instance: "{{ instance_id }}"
            volume_type: "gp2"
            volume_size: 5
            device_name: "sdf"
            state: "present"
            name: "plex-data"
            region: "{{ region }}"
        register: ec2_data_volume
      - ec2_vol:
            instance: "{{ instance_id }}"
            volume_type: "gp2"
            volume_size: 128
            device_name: "sdg"
            state: "present"
            name: "plex-media"
            region: "{{ region }}"
        register: ec2_media_volume

